update env

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -33,30 +33,34 @@ jobs:
       #   run: npm run sonar 
 
       - name: DEBUG variable exists yet 
-        run: | 
-            echo "View variable secrets"
-                if [ -z "${{ secrets.EC2_USER }}" ] || [ -z "${{ secrets.EC2_HOST }}" ] || [ -z "${{ secrets.EC2_SSH_KEY }}" ]; then
-                  echo "❌ One or more secrets are missing"
-                  exit 1
-            fi
-            echo "✅ EC2_SSH_KEY ${{EC2_SSH_KEY}}"
-            echo "✅ EC2_HOST ${{EC2_HOST}}"
-            echo "✅ EC2_USER ${{EC2_USER}}"
-            echo "✅ All secrets are set"
         env:
           EC2_USER: ${{ secrets.EC2_USER }}
           EC2_HOST: ${{ secrets.EC2_HOST }}
           EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
+        run: | 
+            echo "View variable secrets"
+                if [ -z "${ EC2_USER }" ] || [ -z "${ EC2_HOST }" ] || [ -z "${ EC2_SSH_KEY }" ]; then
+                  echo "❌ One or more secrets are missing"
+                  exit 1
+            fi
+            echo "✅ EC2_SSH_KEY ${EC2_SSH_KEY}"
+            echo "✅ EC2_HOST ${EC2_HOST}"
+            echo "✅ EC2_USER ${EC2_USER}"
+            echo "✅ All secrets are set"
+        
+
       - name: Log in to GitHub Container Registry
         uses: docker/login-action@v3
         with:
           registry: ghcr.io
           username: ${{ github.actor }}
           password: ${{ secrets.TOKEN }}
+
       - name: Build image
         run: |
       
           docker build -t ghcr.io/${{ github.repository }}:${{ github.sha }} .
+
       - name: Push image
         uses: docker/build-push-action@v6
         with:
